version: '3'

services:
  ckan:
    build:
      context: .
      args:
        - CKAN_VERSION=2.9.4
        - S3_FILESTORE_VERSION=develop
    depends_on:
      solr:
        condition: service_started
      datapusher:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started
      postgis:
        condition: service_healthy
    environment:
      POSTGRES_READ_HOST: postgis
      POSTGRES_WRITE_HOST: postgis
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DATASTORE_DB: ${POSTGRES_DATASTORE_DB}
      CKAN_SITE_ID: ckan
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      CKAN_SITE_URL: http://localhost:5000
      CKAN_MAX_UPLOAD_SIZE_MB: 100
      S3_BUCKET_NAME: ckan
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
      MINIO_PATH: http://minio:9000
      RUN_INIT_DB: 1
      DATAPUSHER_CALLBACK_URL: http://ckan:5000
      CKAN_DATAPUSHER_URL: http://datapusher:8800
    ports:
      - 5000:5000

  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DATASTORE_DB: ${POSTGRES_DATASTORE_DB}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "ckan"]
      interval: 10s
      timeout: 5s
      retries: 5

  datapusher:
    image: ghcr.io/georepublic/datapusher:latest
    environment:
      CKAN_HOSTNAME: ckan:5000
      DEBUG: 1
      TESTING: 1

  solr:
    image: ghcr.io/georepublic/solr:6.6.6-ckan-2.9.4

  redis:
    image: redis
  
  minio:
    image: minio/minio
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_SERVER_URL: http://localhost:9000
    ports:
      - 9000:9000
      - 9001:9001
