#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname ${POSTGRES_DB} <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS postgis;
    CREATE DATABASE ${POSTGRES_DATASTORE_DB} OWNER ${POSTGRES_USER} ENCODING 'utf-8';
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DATASTORE_DB} TO ${POSTGRES_USER};
    ALTER VIEW geometry_columns OWNER TO ${POSTGRES_USER};
    ALTER TABLE spatial_ref_sys OWNER TO ${POSTGRES_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname ${POSTGRES_DATASTORE_DB} <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS postgis;
EOSQL
